apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pub-metrics-grafana.fullname" . }}-datasources
  labels:
    {{- include "pub-metrics-grafana.labels" . | nindent 4 }}
data:
  datasources.yaml: |-
{{ .Files.Get "datasources" | b64enc | indent 4}}
