{
 "title": "Blockchain State",
 "tags": [ "blockchain" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "query_result(count by (network)(count_over_time(chia_full_node_node_height[$__range])))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Netspace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n        chia_blockchain_netspace_mib{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} or \n        chia_full_node_netspace_mib{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} !=0\n    )\n)",
     "legendFormat": "Netspace"
    }
   ]
  },
  {
   "title": "Netspace Delta",
   "type": "stat",
   "description": "How much the netspace has changed during the selected timeframe",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint)((\n    topk(1, \n        chia_blockchain_netspace_mib{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} or \n        chia_full_node_netspace_mib{application=\"chia-blockchain\", network=\"$network\", component=\"node\"}) !=0))\n- \nsum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint)((\n    topk(1, \n        chia_blockchain_netspace_mib{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} offset $__range or \n        chia_full_node_netspace_mib{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} offset $__range) != 0))",
     "legendFormat": "Netspace"
    }
   ]
  },
  {
   "title": "Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n        chia_blockchain_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} !=0 or \n        chia_full_node_node_height {application=\"chia-blockchain\", network=\"$network\", component=\"node\"} !=0\n    )\n)",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Height Delta",
   "type": "stat",
   "description": "How much the blockchain height has changed by during the selected timeframe",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n        chia_blockchain_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} or \n        chia_full_node_node_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} != 0)) \n- \nsum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n        chia_blockchain_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} offset $__range or \n        chia_full_node_node_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} offset $__range != 0))",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1,\n        chia_blockchain_difficulty{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} or\n        chia_full_node_difficulty{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} !=0 \n    )\n)",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Seconds per Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$__range_s/(\n  sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n      chia_blockchain_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} or\n      chia_full_node_node_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"}\n    ) != 0\n  ) - \n  sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n      chia_blockchain_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} offset $__range or\n      chia_full_node_node_height{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} offset $__range\n    ) != 0\n  )\n)",
     "legendFormat": "Difficulty"
    }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Netspace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, instance_name, namespace, job, instance_name, ref, container, group, endpoint) (\n  topk(1, \n    chia_blockchain_netspace_mib{application=\"chia-blockchain\",network=\"$network\",component=\"node\"} or\n    chia_full_node_netspace_mib{application=\"chia-blockchain\",network=\"$network\",component=\"node\"} != 0\n  )\n)",
     "legendFormat": "Netspace"
    },
    {
     "expr": "topk(1, \n  avg_over_time(job:combined_chia_blockchain_netspace_mib{network=\"$network\",component=\"node\"}[30d]) or \n  avg_over_time(job:combined_chia_full_node_netspace_mib{network=\"$network\",component=\"node\"}[30d])\n)",
     "legendFormat": "30d Average"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n  topk(1, \n    chia_blockchain_difficulty{application=\"chia-blockchain\", network=\"$network\",component=\"node\"} or \n    chia_full_node_difficulty{application=\"chia-blockchain\", network=\"$network\",component=\"node\"} !=0\n  )\n)",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n  topk(1, \n    chia_blockchain_height{application=\"chia-blockchain\",network=\"$network\",component=\"node\"} or\n    chia_full_node_node_height{application=\"chia-blockchain\",network=\"$network\",component=\"node\"} !=0\n  )\n)",
     "legendFormat": "Height"
    },
    {
     "expr": "($__range_s/(\n  sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n      chia_blockchain_height{application=\"chia-blockchain\", network=\"$network\",component=\"node\"} or\n      chia_full_node_node_height{application=\"chia-blockchain\", network=\"$network\",component=\"node\"}\n    ) != 0\n  ) - \n  sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n    topk(1, \n      chia_blockchain_height{application=\"chia-blockchain\", network=\"$network\",component=\"node\"} offset $__range or\n      chia_full_node_node_height{application=\"chia-blockchain\", network=\"$network\",component=\"node\"} offset $__range\n    ) != 0\n  )\n))/18.75",
     "legendFormat": "Blocks per 18.75 seconds"
    }
   ]
  },
  {
   "title": "Compact / Uncompact Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n  topk(1, \n    chia_blockchain_compact_blocks{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} or\n    chia_full_node_compact_blocks{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} !=0\n  )\n)",
     "legendFormat": "Compact"
    },
    {
     "expr": "sum without(pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n  topk(1, \n    chia_blockchain_uncompact_blocks{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} or\n    chia_full_node_uncompact_blocks{application=\"chia-blockchain\", network=\"$network\", component=\"node\"} !=0\n  )\n)",
     "legendFormat": "Uncompact"
    }
   ]
  },
  {
   "title": "Signage Points per 9.375s",
   "type": "timeseries",
   "description": "Shows signage points per 9.375 seconds, averaged over the past 5 minutes. Target value is 1.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "max(rate(chia_full_node_total_signage_points{application=\"chia-blockchain\", network=\"$network\", component=\"node\"}[5m])*9.375)",
     "legendFormat": "SPs/9.375s"
    }
   ]
  },
  {
   "title": "Plot K Size",
   "type": "bargauge",
   "description": "Shows winning plot sizes for the selected timeframe",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(size) (rate(chia_full_node_k_size{application=\"chia-blockchain\", network=\"$network\", component=\"node\"}[$__range])) / ignoring(size) group_left sum(rate(chia_full_node_k_size{application=\"chia-blockchain\", network=\"$network\", component=\"node\"}[$__range])) != 0",
     "legendFormat": "{{size}}"
    }
   ]
  }
 ]
}