{
 "title": "Ecosystem Activity",
 "description": "Metrics acquired about commit activity in repositories identified to be in the Chia ecosystem.",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Chia Ecosystem",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard provides metrics on public commit activity happening on repositories within the broader Chia community."
   }
  },
  { "title": "Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Commit Activity (Total)",
   "type": "stat",
   "description": "Shows number of commits users have made to a Chia ecosystem repository in total history.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecosystem_activity",
     "rawSql": "SELECT COUNT(*) AS row_count\nFROM ecosystem_activity.commits\n"
    }
   ]
  },
  {
   "title": "Commit Activity (Date Range)",
   "type": "stat",
   "description": "Shows number of unique commits that have been made within the given dashboard time range.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecosystem_activity",
     "rawSql": "SELECT COUNT(*) AS row_count\nFROM ecosystem_activity.commits\nWHERE date BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Total Ecosystem Commits (Over Time)",
   "type": "timeseries",
   "description": "This graph represents the over-time activity in identified Chia ecosystem repositories.\n\nThe data in this time series graph is updated on a nightly schedule.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \nUNIX_TIMESTAMP(date) AS time_sec,\nid AS '# Commits'\nFROM ecosystem_activity.sorted_commits\nWHERE $__timeFilter(date)\nORDER BY date ASC"
    }
   ]
  },
  { "title": "Repositories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Repositories (Total)",
   "type": "stat",
   "description": "Shows the total number of unique repositories in the Chia ecosystem.\n\nThis number includes repositories that may no longer exist on GitHub (either deleted by GitHub or the repository owner). We retain all historical data for consistency of metrics over time, even if the repositories no longer exist",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecosystem_activity",
     "rawSql": "SELECT COUNT(*) AS row_count\nFROM ecosystem_activity.repos"
    }
   ]
  },
  {
   "title": "Repo Activity (Latest commit in date range)",
   "type": "stat",
   "description": "Shows number of unique repos that have had a commit within the given dashboard time range.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecosystem_activity",
     "rawSql": "SELECT COUNT(*) AS row_count\nFROM ecosystem_activity.repos\nWHERE last_commit BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  { "title": "Developers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Developers with Commit Activity (Total)",
   "type": "stat",
   "description": "Shows number of unique developers that have made a commit to a Chia ecosystem repository in total history.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecosystem_activity",
     "rawSql": "SELECT COUNT(*) AS row_count\nFROM ecosystem_activity.users\n"
    }
   ]
  },
  {
   "title": "Developer Activity (First commit in date range)",
   "type": "stat",
   "description": "Shows number of unique developers that have made their first commit to a Chia ecosystem repo within the given dashboard time range.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecosystem_activity",
     "rawSql": "SELECT COUNT(*) AS row_count\nFROM ecosystem_activity.users\nWHERE first_commit BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  },
  {
   "title": "Developer Activity (Latest commit in date range)",
   "type": "stat",
   "description": "Shows number of unique developers that have made any commits within the given dashboard time range.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecosystem_activity",
     "rawSql": "SELECT COUNT(*) AS row_count\nFROM ecosystem_activity.users\nWHERE last_commit BETWEEN $__timeFrom() AND $__timeTo()"
    }
   ]
  }
 ]
}