{
 "title": "Mempool, Transactions, & Fees",
 "tags": [ "blockchain" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "query_result(count by (network)(count_over_time(chia_full_node_node_height[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mempool Spendbundle Count",
   "type": "timeseries",
   "description": "How many individual spendbundles are currently in the mempool\n\nSpendbundle Docs: https://docs.chia.net/spend-bundles/",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, \n    (\n      chia_full_node_mempool_size{network=\"$network\"} and on (instance) (chia_full_node_node_synced{network=\"$network\"} == 1)\n    ) or\n    chia_blockchain_mempool_size{network=\"$network\"}\n  )\n)",
     "legendFormat": "Spends"
    }
   ]
  },
  {
   "title": "Mempool Cost",
   "type": "timeseries",
   "description": "This shows the current cost of the mempool (how full the mempool is). Once the mempool is full, a fee is required to kick other lower fee transactions out to get your transaction included in the mempool.\n\nOnce a transaction is in the mempool, it will be included in blocks as there is space. Typically the highest \"fee per cost\" are included in blocks first.\n\nCost Info: https://chialisp.com/costs/\nMempool Info: https://docs.chia.net/mempool/",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_mempool_cost{network=\"$network\"} and on (instance) (chia_full_node_node_synced{network=\"$network\"} == 1))\n) !=0",
     "legendFormat": "Mempool Cost"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_mempool_max_total_cost{network=\"$network\"})!=0\n)",
     "legendFormat": "Max Cost"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transactions / Second (Estimated)",
   "type": "timeseries",
   "description": "This is based on a transaction of 5,000,000 cost (estimated standard transaction cost). Since cost can vary based on a number of factors, the true number of transactions will vary.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_block_cost{network=\"$network\"}) / 5000000\n) * \nsum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  bottomk(1,  \n    rate(chia_full_node_node_height{network=\"$network\"}[5m]) and on (instance) (chia_full_node_node_synced{network=\"$network\"} == 1)\n  )\n) / 3",
     "legendFormat": "5,000,000 Cost TX"
    }
   ]
  },
  {
   "title": "Block Percent Full",
   "type": "timeseries",
   "description": "How full each block is. Currently, there is a cap of 50%.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_block_cost{network=\"$network\"} and on (instance) (chia_full_node_node_synced{network=\"$network\"} == 1))\n) /\nsum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_block_max_cost{network=\"$network\"})\n)",
     "legendFormat": "Instant"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n    sum_over_time(chia_full_node_block_cost{network=\"$network\"}[1h])\n)\n/\n(\n    sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n        count_over_time(chia_full_node_block_cost{network=\"$network\"}[1h])\n    )  \n    *\n    sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint) (\n        topk(1, chia_full_node_block_max_cost{network=\"$network\"})\n    )\n)\n",
     "legendFormat": "1h Trailing"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n    sum_over_time(chia_full_node_block_cost{network=\"$network\"}[1d])\n)\n/\n(\n    sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n        count_over_time(chia_full_node_block_cost{network=\"$network\"}[1d])\n    )  \n    *\n    sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n        topk(1, chia_full_node_block_max_cost{network=\"$network\"})\n    )\n)\n",
     "legendFormat": "1d Trailing"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n    sum_over_time(chia_full_node_block_cost{network=\"$network\"}[7d])\n)\n/\n(\n    sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n        count_over_time(chia_full_node_block_cost{network=\"$network\"}[7d])\n    )  \n    *\n    sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n        topk(1, chia_full_node_block_max_cost{network=\"$network\"})\n    )\n)\n",
     "legendFormat": "7d Trailing"
    },
    { "expr": ".5", "legendFormat": "Current Block Cap" }
   ]
  },
  {
   "title": "Smart Transactions (Hint Count)",
   "type": "timeseries",
   "description": "Total number of smart transactions to date (CATs, NFTs, etc)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, \n    chia_full_node_hint_count{network=\"$network\"} or\n    chia_blockchain_hint_count{network=\"$network\"}\n  )\n)",
     "legendFormat": "Hint Count"
    }
   ]
  },
  {
   "title": "Fees",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Fees",
   "type": "timeseries",
   "description": "This shows the sum of fees that were actually paid for transactions that have been included in blocks.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_block_fees{network=\"$network\",component!~\"bluebox\"})\n) / 1000000000000",
     "legendFormat": "Instant"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  sum_over_time(chia_full_node_block_fees{network=\"$network\",component!~\"bluebox\"}[1h])\n) \n/\nsum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  count_over_time(chia_full_node_block_fees{network=\"$network\",component!~\"bluebox\"}[1h])\n) \n/ 1000000000000",
     "legendFormat": "1h Trailing"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  sum_over_time(chia_full_node_block_fees{network=\"$network\",component!~\"bluebox\"}[1d])\n) \n/\nsum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  count_over_time(chia_full_node_block_fees{network=\"$network\",component!~\"bluebox\"}[1d])\n) \n/ 1000000000000",
     "legendFormat": "1d Trailing"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  sum_over_time(chia_full_node_block_fees{network=\"$network\",component!~\"bluebox\"}[7d])\n) \n/\nsum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  count_over_time(chia_full_node_block_fees{network=\"$network\",component!~\"bluebox\"}[7d])\n) \n/ 1000000000000",
     "legendFormat": "7d Trailing"
    }
   ]
  },
  {
   "title": "Fee Estimate - Send XCH",
   "type": "timeseries",
   "description": "Shows the current fee estimate for an average \"send xch\" transaction for the specified target block inclusion timeframes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"send-xch\", time=\"60\"})/1000000000000\n)",
     "legendFormat": "1m Target"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"send-xch\", time=\"300\"})/1000000000000\n)",
     "legendFormat": "5m Target"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"send-xch\", time=\"900\"})/1000000000000\n)",
     "legendFormat": "15m Target"
    }
   ]
  },
  {
   "title": "Fee Estimate - Send Cat",
   "type": "timeseries",
   "description": "Shows the current fee estimate for an average \"send cat\" transaction for the specified target block inclusion timeframes.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"send-cat\", time=\"60\"})/1000000000000\n)",
     "legendFormat": "1m Target"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"send-cat\", time=\"300\"})/1000000000000\n)",
     "legendFormat": "5m Target"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"send-cat\", time=\"900\"})/1000000000000\n)",
     "legendFormat": "15m Target"
    }
   ]
  },
  {
   "title": "Fee Estimate - Transfer NFT",
   "type": "timeseries",
   "description": "Shows the current fee estimate for an average \"transfer nft\" transaction for the specified target block inclusion timeframes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"tx-nft\", time=\"60\"})/1000000000000\n)",
     "legendFormat": "1m Target"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"tx-nft\", time=\"300\"})/1000000000000\n)",
     "legendFormat": "5m Target"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"tx-nft\", time=\"900\"})/1000000000000\n)",
     "legendFormat": "15m Target"
    }
   ]
  },
  {
   "title": "Fee Estimate - Take Offer",
   "type": "timeseries",
   "description": "Shows the current fee estimate for an average \"take offer\" transaction for the specified target block inclusion timeframes.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"take-offer\", time=\"60\"})/1000000000000\n)",
     "legendFormat": "1m Target"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"take-offer\", time=\"300\"})/1000000000000\n)",
     "legendFormat": "5m Target"
    },
    {
     "expr": "sum without(cluster, application, component, pod, service, instance, namespace, job, instance_name, ref, container, group, endpoint, region) (\n  topk(1, chia_full_node_fee_estimate{network=\"$network\", type=\"take-offer\", time=\"900\"})/1000000000000\n)",
     "legendFormat": "15m Target"
    }
   ]
  }
 ]
}